language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
before_script:
  - npm install
script:
  - docker build -t my-frontend .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag my-frontend $DOCKER_USER/my-frontend:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/my-frontend:$TRAVIS_BUILD_NUMBER
  - docker tag my-frontend $DOCKER_USER/my-frontend:latest
  - docker push $DOCKER_USER/my-frontend:latest